blog/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.signup 'signup', :controller => 'users', :action => 'new'
  map.logout 'logout', :controller => 'user_sessions', :action => 'destroy'
  map.login 'login', :controller => 'user_sessions', :action => 'new'
  map.resources :user_sessions

  map.resources :users

  map.resources :articles, :comments
  map.root :articles
end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  validates_presence_of :name, :content
  belongs_to :user
end

blog/app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  validates_presence_of :author_name, :content
end

blog/app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, :through => :assignments
end

blog/app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :articles
  has_many :comments
  has_many :assignments
  has_many :roles, :through => :assignments
  
  def role_symbols
    roles.map do |role|
      role.name.underscore.to_sym
    end
  end
end

blog/app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

blog/app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  include Authentication
  helper :all
  protect_from_forgery
  before_filter { |c| Authorization.current_user = c.current_user }
  
  protected
  
  def permission_denied
    flash[:error] = "Sorry, you are not allowed to access that page."
    redirect_to root_url
  end
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  filter_resource_access
  
  def index
    @articles = Article.find(:all)
  end
  
  def show
    @comment = Comment.new(:article => @article)
  end
  
  def new
  end
  
  def create
    @article.user = current_user
    if @article.save
      flash[:notice] = "Successfully created article."
      redirect_to @article
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @article.update_attributes(params[:article])
      flash[:notice] = "Successfully updated article."
      redirect_to @article
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @article.destroy
    flash[:notice] = "Successfully destroyed article."
    redirect_to articles_url
  end
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  filter_resource_access
  
  def new
  end
  
  def create
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to article_url(@comment.article_id)
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @comment.update_attributes(params[:comment])
      flash[:notice] = "Successfully updated comment."
      redirect_to article_url(@comment.article_id)
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @comment.destroy
    flash[:notice] = "Successfully destroyed comment."
    redirect_to article_url(@comment.article_id)
  end
end

blog/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end
  
  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Logged in successfully."
      redirect_to_target_or_default(root_url)
    else
      render :action => 'new'
    end
  end
  
  def destroy
    @user_session = UserSession.find
    @user_session.destroy
    flash[:notice] = "You have been logged out."
    redirect_to root_url
  end
end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Thank you for signing up! You are now logged in."
      redirect_to root_url
    else
      render :action => 'new'
    end
  end
end

blog/app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    @content_for_title = page_title.to_s
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args.map(&:to_s)) }
  end
  
  def javascript(*args)
    args = args.map { |arg| arg == :defaults ? arg : arg.to_s }
    content_for(:head) { javascript_include_tag(*args) }
  end
end

blog/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/views/articles/_form.html.erb
<%= error_messages_for :article %>
<% form_for @article do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.label :author_name %><br />
    <%= f.text_field :author_name %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

blog/app/views/articles/edit.html.erb
<% title "Edit Article" %>

<%= render :partial => 'form' %>

<p>
  <%= link_to "Show", @article %> |
  <%= link_to "View All", articles_path %>
</p>

blog/app/views/articles/index.html.erb
<% title "Articles" %>

<div id="articles">
<% for article in @articles %>
  <h2>
    <%= link_to h(article.name), article %>
    <span class="comments">(<%= pluralize(article.comments.size, 'comment') %>)</span>
  </h2>
  <div class="author">from <%=h article.author_name %> on <%= article.created_at.strftime('%b %d, %Y') %></div>
  <div class="content"><%= simple_format(article.content) %></div>
<% end %>
</div>

<% if permitted_to? :create, Article.new %>
  <p><%= link_to "New Article", new_article_path %></p>
<% end %>

blog/app/views/articles/new.html.erb
<% title "New Article" %>

<%= render :partial => 'form' %>

<p><%= link_to "Back to List", articles_path %></p>

blog/app/views/articles/show.html.erb
<% title @article.name %>

<p class="author"><em>from <%=h @article.author_name %></em></p>

<%= simple_format @article.content %>

<p>
  <% if permitted_to? :edit, @article %>
    <%= link_to "Edit", edit_article_path(@article) %> |
  <% end %>
  <% if permitted_to? :destroy, @article %>
    <%= link_to "Destroy", @article, :method => :delete, :confirm => "Are you sure?" %> |
  <% end %>
  <%= link_to "Back to Articles", articles_path %>
</p>

<% unless @article.comments.empty? %>
  <h2><%= pluralize(@article.comments.size, 'comment') %></h2>

  <div id="comments">
  <% for comment in @article.comments %>
    <div class="comment">
      <strong><%= link_to_unless comment.site_url.blank?, h(comment.author_name), h(comment.site_url) %></strong>
      <em>on <%= comment.created_at.strftime('%b %d, %Y at %H:%M') %></em>
      <%=simple_format comment.content %>
      <p>
        <% if permitted_to? :edit, comment %>
          <%= link_to "Edit", edit_comment_path(comment) %>
        <% end %>
        <% if permitted_to? :destroy, comment %>
          | <%= link_to "Destroy", comment, :method => :delete, :confirm => "Are you sure?" %>
        <% end %>
      </p>
    </div>
  <% end %>
  </div>
<% end %>

<% if permitted_to? :create, @comment %>
  <h3>Add your comment:</h3>
  <%= render :partial => 'comments/form' %>
<% end %>

blog/app/views/comments/_form.html.erb
<%= error_messages_for :comment %>
<% form_for @comment do |f| %>
  <%= f.hidden_field :article_id %>
  <p>
    <%= f.label :author_name, 'Name' %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :site_url, 'Website URL' %><br />
    <%= f.text_field :site_url %>
  </p>
  <p>
    <%= f.label :content, 'Comment' %><br />
    <%= f.text_area :content, :rows => '12', :cols => 35 %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

blog/app/views/comments/edit.html.erb
<% title "Edit Comment" %>

<%= render :partial => 'form' %>

blog/app/views/comments/new.html.erb
<% title "New Comment" %>

<%= render :partial => 'form' %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title><%= h(yield(:title) || "Untitled") %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <div id="user_status">
        <% if logged_in? %>
          Welcome <%=h current_user.username %>! Not you?
          <%= link_to "Log out", logout_path %>
        <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "log in", login_path %>.
        <% end %>
      </div>
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
      
      <%- if show_title? -%>
        <h1><%=h yield(:title) %></h1>
      <%- end -%>
      
      <%= yield %>
    </div>
  </body>
</html>

blog/app/views/user_sessions/new.html.erb
<% title "Log in" %>

<p>Don't have an account? <%= link_to "Sign up!", signup_path %></p>

<% form_for @user_session do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p><%= f.submit "Log in" %></p>
<% end %>

blog/app/views/users/new.html.erb
<% title "Sign up" %>

<p>Already have an account? <%= link_to "Log in", login_path %>.</p>

<% form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation, "Confirm Password" %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :roles %><br />
    <% for role in Role.all %>
      <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
      <%=h role.name %><br />
    <% end %>
  </p>
  <p><%= f.submit "Sign up" %></p>
<% end %>